version: "3"

services:
    db:
        image: postgres:11-alpine
    app:
        build:
            context: .
        ports:
            - "8080:8080"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8080"
        env_file:
            - .env
        depends_on:
            - db
