# Generated by Django 2.2.1 on 2019-05-27 00:14

import app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(default='', storage=app.storage_backends.PrivateMediaStorage(), upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='upload',
            name='file',
            field=models.FileField(default='', storage=app.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
