# Generated by Django 2.2.1 on 2019-06-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20190528_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadprivate',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
