# Generated by Django 2.2.1 on 2019-06-22 20:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0004_auto_20190622_2017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload',
            new_name='Photo',
        ),
        migrations.DeleteModel(
            name='UploadPrivate',
        ),
    ]
