# Generated by Django 2.2.1 on 2019-06-22 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0005_auto_20190622_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='demo.Photo')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
