# Generated by Django 2.2.1 on 2019-06-22 20:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0006_auto_20190622_2043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DashboardSettings',
            new_name='DashboardSetting',
        ),
    ]
