# Generated by Django 2.2.1 on 2019-06-23 00:25

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20190622_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=slugger.fields.AutoSlugField(default='needs-slug', populate_from='title'),
        ),
    ]
