# Generated by Django 2.2.1 on 2019-06-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_photo_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='galleries',
            field=models.ManyToManyField(to='demo.Gallery'),
        ),
    ]
