# Generated by Django 2.2.1 on 2019-07-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='galleries',
            field=models.ManyToManyField(blank=True, to='core.Gallery'),
        ),
    ]
