# Generated by Django 2.2.1 on 2019-07-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190701_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cover_photo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Photo'),
        ),
    ]
