# Generated by Django 2.2.3 on 2019-08-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_menuitem_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_type',
            field=models.CharField(choices=[('MA', 'Masonry'), ('MU', 'Museum')], default='MA', max_length=2),
        ),
    ]
