# Generated by Django 2.2.3 on 2019-08-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gallery_gallery_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='gallery_type',
            new_name='type',
        ),
    ]
