# Generated by Django 2.2.3 on 2019-08-07 07:03

from django.db import migrations, models
import django.db.models.deletion
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190804_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=slugger.fields.AutoSlugField(default='needs-slug', populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=slugger.fields.AutoSlugField(default='needs-slug', populate_from='title', unique=True),
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=50, unique=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Gallery')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Photo')),
            ],
        ),
    ]
