# Generated by Django 2.2.3 on 2019-08-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190815_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='subGalleries',
            field=models.ManyToManyField(blank=True, to='core.Gallery'),
        ),
    ]
