# Generated by Django 2.2.3 on 2019-08-26 06:00

import app.storage_backends
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190826_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', tinymce.models.HTMLField()),
                ('aboveBannerText', models.CharField(max_length=128)),
                ('bannerText', models.CharField(max_length=128)),
                ('belowBannerText', models.CharField(max_length=128)),
                ('pictureLink', models.FileField(default='', storage=app.storage_backends.PublicMediaStorage(), upload_to='')),
                ('customClass', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='layout',
            name='rank',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='page',
            name='sections',
            field=models.ManyToManyField(default=None, through='core.Layout', to='core.Section'),
        ),
        migrations.AddField(
            model_name='layout',
            name='splitSection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.SplitSection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='splitSections',
            field=models.ManyToManyField(default=None, through='core.Layout', to='core.SplitSection'),
        ),
    ]
