# Generated by Django 2.2.3 on 2019-08-26 06:14

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190826_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=slugger.fields.AutoSlugField(null=True, populate_from='title', unique=True),
        ),
    ]
