# Generated by Django 2.2.3 on 2019-08-26 06:15

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=slugger.fields.AutoSlugField(default='needs-slug', null=True, populate_from='title', unique=True),
        ),
    ]
