# Generated by Django 2.2.3 on 2019-08-26 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190826_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Section'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='splitSection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.SplitSection'),
        ),
    ]
