# Generated by Django 2.2.3 on 2019-08-26 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190826_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='page',
            name='splitSections',
        ),
        migrations.AlterField(
            model_name='layout',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtm', to='core.Page'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtm', to='core.Section'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='splitSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtm', to='core.SplitSection'),
        ),
    ]
