# Generated by Django 2.2.3 on 2019-08-26 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190826_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtm', to='core.Page'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtm', to='core.Section'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='splitSection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtm', to='core.SplitSection'),
        ),
    ]
